### ISSUE TITLE
pip3 install not working - missing dependencies for IDE

### ISSUE THREAD

**Issue by hellocatfood** [shoebot/shoebot#269] opened 2020-04-15 22:16 UTC
I'm trying to install shoebot on Ubuntu 19.10 using the following command:
`pip3 install shoebot`
The installation appears to be successful. However, when I run `shoebot` I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/shoebot", line 11, in <module>
    load_entry_point('shoebot==1.3.1', 'gui_scripts', 'shoebot')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/shoebot-1.3.1-py3.7.egg/shoebot/ide/ide.py", line 15, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 133, in require_version
    (namespace, version))
ValueError: Namespace GtkSource not available for version 3.0
```

**Comment by rlafuente** [comment] 2020-04-15 22:25
This probably has to do with either pgi or gtksourceview not being installed -- any clue @stuaxo ?

**Comment by hellocatfood** [comment] 2020-04-15 22:36
I have libgtksourceview-4-0 and already libgtksourceview-3-0.1 installed. I tried installing python-gtksourceview2 but it had no effect.

**Comment by stuaxo** [comment] 2020-04-16 11:38
Try installing dependencies + trying again:

`sudo apt install build-essential gir1.2-rsvg-2.0 gobject-introspection libglib2.0-dev libgirepository1.0-dev libjpeg-dev python-gi-cairo python-gobject python3-dev`

**Comment by hellocatfood** [comment] 2020-04-16 12:47
I ran the code you posted and of those I didn't have `python3-mako python3-markdown`. Installing those also installed `libgirepository1.0-doc python3-beaker python-mako-doc python-markdown-doc`

I uninstalled and reinstalled shoebot (`pip3 install shoebot`) and when I ran shoebot I got this error
```
Traceback (most recent call last):
  File "/usr/local/bin/shoebot", line 11, in <module>
    load_entry_point('shoebot==1.3.1', 'gui_scripts', 'shoebot')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/hellocatfood/.local/lib/python3.7/site-packages/shoebot/__init__.py", line 36, in <module>
    from shoebot.core.backend import cairo
  File "/home/hellocatfood/.local/lib/python3.7/site-packages/shoebot/core/__init__.py", line 38, in <module>
    from canvas import Canvas
ModuleNotFoundError: No module named 'canvas'
```

**Comment by stuaxo** [comment] 2020-04-16 13:12
This looks like a bug that is fixed in git but not yet released, you can try installing from here and see if things work better:

`$ pip install git+https://github.com/shoebot/shoebot.git@master#egg=shoebot`

**Comment by hellocatfood** [comment] 2020-04-16 13:38
I installed that but still got the same error
```
Traceback (most recent call last):
  File "/home/hellocatfood/.local/bin/shoebot", line 6, in <module>
    from shoebot.ide.ide import main
  File "/home/hellocatfood/.local/lib/python3.7/site-packages/shoebot/__init__.py", line 36, in <module>
    from shoebot.core.backend import cairo
  File "/home/hellocatfood/.local/lib/python3.7/site-packages/shoebot/core/__init__.py", line 38, in <module>
    from canvas import Canvas
ModuleNotFoundError: No module named 'canvas'
```
So, I tried installing canvas (`pip3 install canvas`) and then ran shoebot.
```
Traceback (most recent call last):
  File "/home/hellocatfood/.local/bin/shoebot", line 6, in <module>
    from shoebot.ide.ide import main
  File "/home/hellocatfood/.local/lib/python3.7/site-packages/shoebot/__init__.py", line 36, in <module>
    from shoebot.core.backend import cairo
  File "/home/hellocatfood/.local/lib/python3.7/site-packages/shoebot/core/__init__.py", line 38, in <module>
    from canvas import Canvas
  File "/home/hellocatfood/.local/lib/python3.7/site-packages/canvas.py", line 5, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'
```

**Comment by stuaxo** [comment] 2020-04-16 14:04
Apologies, I wrote pip instead of pip3.

You will need to uninstall canvas :)

Try running hash -r and running again.


If that doesn't work, remove the folder 

/home/hellocatfood/.local/lib/python3.7/site-packages/shoebot

Reinstall the version from git (the command I pasted, but with pip3).

And try again.

Paste me the output from trying to install from git, if things don't work.

**Comment by hellocatfood** [comment] 2020-04-16 17:01
I uninstalled canvas and went into the python folders in .local to check if there were any conflicting packages or traces of older shoebot installation attempts. I then ran `pip3 install git+https://github.com/shoebot/shoebot.git@master#egg=shoebot`

Output as it was installing:
```
Collecting shoebot from git+https://github.com/shoebot/shoebot.git@master#egg=shoebot
  Cloning https://github.com/shoebot/shoebot.git (to revision master) to /tmp/pip-install-ug4cjcki/shoebot
Requirement already satisfied: Pillow>=6.0.0 in /usr/lib/python3/dist-packages (from shoebot) (6.1.0)
Requirement already satisfied: meta==1.0.2 in /usr/local/lib/python3.7/dist-packages/meta-1.0.2-py3.7.egg (from shoebot) (1.0.2)
Requirement already satisfied: pubsub==0.1.2 in ./.local/lib/python3.7/site-packages (from shoebot) (0.1.2)
Requirement already satisfied: pycairo>=1.18.1 in ./.local/lib/python3.7/site-packages (from shoebot) (1.19.1)
Requirement already satisfied: pygobject>=3.32.1 in /usr/lib/python3/dist-packages (from shoebot) (3.34.0)
Requirement already satisfied: setuptools>=18.8 in /usr/lib/python3/dist-packages (from shoebot) (41.1.0)
Requirement already satisfied: six<2,>=1 in /usr/lib/python3/dist-packages (from pubsub==0.1.2->shoebot) (1.12.0)
Building wheels for collected packages: shoebot
  Running setup.py bdist_wheel for shoebot ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-zzl3qtx7/wheels/bd/63/72/6b6634ae8758608f0fc6aeaaaf2eadbddc84b0d3dfb00a3160
Successfully built shoebot
Installing collected packages: shoebot
Successfully installed shoebot-1.3.1
```
After running `shoebot`
```
Traceback (most recent call last):
  File "/home/hellocatfood/.local/bin/shoebot", line 6, in <module>
    from shoebot.ide.ide import main
  File "/home/hellocatfood/.local/lib/python3.7/site-packages/shoebot/ide/ide.py", line 15, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 133, in require_version
    (namespace, version))
ValueError: Namespace GtkSource not available for version 3.0
```
In my packages I have python-gtksourceview2 but even when I install it shoebot reports the same error. I'm guessing python-gtksourceview2 is for python 2.7 and there needs to be one for python 3?

**Comment by stuaxo** [comment] 2020-04-16 20:23
I think it may be the gtk2 version.

I think the newer versions don't need a specific `python-`  because they work via gobject.

Does the `sbot` command work ?

I need to get a clean vm and try to reproduce your bug.

It might be as simple as me not testing the idea:/

**Comment by hellocatfood** [comment] 2020-04-16 21:07
`sbot` is working

**Comment by stuaxo** [comment] 2020-04-16 21:59
I reproduced this in a vm, and was able to fix it by installing libgtksourceview-3.0-dev:

`sudo apt install libgtksourceview-3.0-dev -y`

Let me know if that gets things working.

**Comment by hellocatfood** [comment] 2020-04-16 22:19
It works!!! Well, the IDE window opens. I'll start learning and using the program and report if there's any other problems. Thanks for your help.

**Comment by stuaxo** [comment] 2020-04-16 22:36
Great :)

As a heads up:   The IDE hasn't been updated, so if things don't work, try `sbot` to see if there are any differences.

Have fun, and let us know what you find.

I'm going to leave this open so I remember to add the missing dependency.

**Comment by stuaxo** [comment] 2020-04-23 01:12
I'm closing this, as dependencies have been added to master and we now have tests on travis to detect the issue you found.

I'm going on a bit of a bugfixing round at the moment, cheers for finding this.

**Closed by stuaxo** 2020-04-23 01:12 UTC
