### ISSUE TITLE
filled circles exported as svg are not correcly imported in inkscape

### ISSUE THREAD

**Issue by aoloe** [shoebot/shoebot#234] opened 2019-06-01 11:31 UTC
```py
fill(1, 0, 0)
for i in range(3):
    oval(10, 10 + 60 * i, 50, 50)

stroke(0)
nofill()

for i in range(2):
    oval(10, 190 + 60 * i, 50, 50)
```

i i run:

```
sbot circlesl.bot -o circles.svg
```

the resulting svg can be load in inkscape and:

- the two hollow circles are paths (and fine)
- but the three filled ones are of an _undefined_ type and cannot be further edited...

[circles.zip](https://github.com/shoebot/shoebot/files/3243705/circles.zip)

**Comment by rlafuente** [comment] 2019-06-01 21:53
Good find -- for some reason, the filled circles are saved in the SVG as images:

```xml
<image id="image18" width="1667" height="1667" 
xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSU
hEUgAABoMAAAaDCAYAAAAl+FcfAAAABmJLR0QA/wD
/AP+gvaeTAAAgAElEQVR4nOzde8y+d0Hf8fdFbUsHBWz
BMgVsheHWjdOgFOk2I1AGcsYhjkghhBBNNrJDFrVDHNl
MXCaRRsjCFLdYHFqDKONMFYeUisDsCoKAQNUyofRg
(...)
```

There would be the possibility of it being a Cairo problem, but I've just tried a quick script using Pycairo and it renders SVG with the filled shapes as you would expect.

This will need some thorough debugging to read exactly how Shoebot is calling Cairo commands to draw filled shapes. It should not be doing more than

    context.set_source_rgba(1, 0.2, 0.2, 0.6)
    context.rectangle(0.4, 0.4, 0.6, 0.6)
    context.fill()

I'll find some time to dig up what commands are being passed to Cairo. Thanks again for noticing this subtle but pretty important detail.

**Comment by stuaxo** [comment] 2019-06-03 15:38
Arg - that is a pain.

We use recording surfaces a lot (which I would not expect to convert things to bitmaps), I believe I did some tests a while ago and saw the same thing.

@rlafuente 

cairo_canvas.ellipse_closure is what oval eventually calls
https://github.com/shoebot/shoebot/blob/master/shoebot/core/cairo_canvas.py#L108

(simplifying)
```.oval() --> bezier.ellipse() --> ellipse_closure()```

**Comment by stuaxo** [comment] 2020-02-26 20:36
Roughly:

The first context is a recording surface
```python
    context.set_source_rgba(1, 0.2, 0.2, 0.6)
    context.rectangle(0.4, 0.4, 0.6, 0.6)
    context.fill()
```

Which is then used as a source to draw on the destination surface SVGSurface in this case.

We should try and make a short script of that and see if it does the same thing.

From what the cairo devs said vectors from a recording surface should remain vectors.

**Comment by stuaxo** [comment] 2020-02-26 23:15
The (good?) news is that I can't reproduce this, with a simple recording surface -> svg surface.

https://gist.github.com/stuaxo/2d9629652b5125cc58959182822dd329

So either the bug does exactly what it looks like, or it's because we do something a bit more complex in our drawing.

The way we compose outlines and fills may be confusing it:

https://github.com/shoebot/shoebot/blob/master/shoebot/data/bezier.py#L273

```python
    # Draw onto intermediate surface so that stroke
    # does not overlay fill
    cairo_ctx.push_group()

    cairo_ctx.set_source_rgba(*fillcolor)
    cairo_ctx.fill_preserve()

    e = cairo_ctx.stroke_extents()
    cairo_ctx.set_source_rgba(*strokecolor)
    cairo_ctx.set_operator(cairo.OPERATOR_SOURCE)
    cairo_ctx.set_line_width(strokewidth)
    cairo_ctx.stroke()

    cairo_ctx.pop_group_to_source()
    cairo_ctx.paint()
```

So is the next thing to reproduce.

**Comment by rlafuente** [comment] 2021-04-04 22:28
fixed in https://github.com/shoebot/shoebot/pull/359 !

**Closed by rlafuente** 2021-04-04 22:28 UTC
Labels: bug
