### ISSUE TITLE
colorMode doesn't work inside setup

### ISSUE THREAD

**Issue by azbulutlu** [shoebot/shoebot#233] opened 2019-06-01 11:26 UTC
not sure if this is intended behavior
```python
def setup():
    colormode(HSB)
    size(500,500)
    background(1,0,1)
```
colormode simply gets ignored inside the function. On outside it works

**Comment by stuaxo** [comment] 2019-06-03 15:21
Thanks, definitely a bug - colormode should be persistent.

**Comment by rlafuente** [comment] 2019-06-03 22:31
This probably is related to the run-3-times bug (#247), see the output there

**Comment by stuaxo** [comment] 2021-02-04 15:30
Closing as a dupe of #247

**Closed by stuaxo** 2021-02-04 15:30 UTC
Labels: bug
